//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Academy_Fitness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseRegistration
    {
        public int ID { get; set; }
        public int TrainerID { get; set; }
        public int CourseID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsDone { get; set; }
        public int TotalPoint { get; set; }
        public string Comment { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
